/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nekomeshi312.selfcamera.jni;

public class CpuCheck {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CpuCheck(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CpuCheck obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        selfcameraJNI.delete_CpuCheck(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CpuCheck() {
    this(selfcameraJNI.new_CpuCheck(), true);
  }

  public boolean NeonCheck() {
    return selfcameraJNI.CpuCheck_NeonCheck(swigCPtr, this);
  }

}
