/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nekomeshi312.selfcamera.jni;



/** FaceDetect - for processing images that are stored in an image pool
*/
public class FaceDetect {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FaceDetect(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FaceDetect obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        selfcameraJNI.delete_FaceDetect(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FaceDetect() {
    this(selfcameraJNI.new_FaceDetect(), true);
  }

  public boolean init(int width, int height, String cascade_name, byte[] errorcode) {
    return selfcameraJNI.FaceDetect_init(swigCPtr, this, width, height, cascade_name, errorcode);
  }

  public int detectFacePos(byte[] img, int[] result, int max_num, int orientation) {
    return selfcameraJNI.FaceDetect_detectFacePos(swigCPtr, this, img, result, max_num, orientation);
  }

  public final static int ROTATION_0 = selfcameraJNI.FaceDetect_ROTATION_0_get();
  public final static int ROTATION_90 = selfcameraJNI.FaceDetect_ROTATION_90_get();
  public final static int ROTATION_180 = selfcameraJNI.FaceDetect_ROTATION_180_get();
  public final static int ROTATION_270 = selfcameraJNI.FaceDetect_ROTATION_270_get();
  public final static int ROTATION_UNKNOWN = selfcameraJNI.FaceDetect_ROTATION_UNKNOWN_get();

}
