/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nekomeshi312.selfcamera.jni;

public class FaceDetectRect {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FaceDetectRect(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FaceDetectRect obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        selfcameraJNI.delete_FaceDetectRect(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLeft(int value) {
    selfcameraJNI.FaceDetectRect_left_set(swigCPtr, this, value);
  }

  public int getLeft() {
    return selfcameraJNI.FaceDetectRect_left_get(swigCPtr, this);
  }

  public void setTop(int value) {
    selfcameraJNI.FaceDetectRect_top_set(swigCPtr, this, value);
  }

  public int getTop() {
    return selfcameraJNI.FaceDetectRect_top_get(swigCPtr, this);
  }

  public void setRight(int value) {
    selfcameraJNI.FaceDetectRect_right_set(swigCPtr, this, value);
  }

  public int getRight() {
    return selfcameraJNI.FaceDetectRect_right_get(swigCPtr, this);
  }

  public void setBottom(int value) {
    selfcameraJNI.FaceDetectRect_bottom_set(swigCPtr, this, value);
  }

  public int getBottom() {
    return selfcameraJNI.FaceDetectRect_bottom_get(swigCPtr, this);
  }

  public FaceDetectRect() {
    this(selfcameraJNI.new_FaceDetectRect(), true);
  }

}
