/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.nekomeshi312.selfcamera.jni;

public class selfcameraJNI {

	static {
		try {
			//load the selfcamera library, make sure that libselfcamera.so is in your <project>/libs/armeabi directory
			//so that android sdk automatically installs it along with the app.
			
			//the android-opencv lib must be loaded first inorder for the selfcamera
			//lib to be found
			//check the apk generated, by opening it in an archive manager, to verify that
			//both these libraries are present
			System.loadLibrary("selfcamera");
		} catch (UnsatisfiedLinkError e) {
			//badness
			throw e;
		}
	}


  public final static native void FaceDetectRect_left_set(long jarg1, FaceDetectRect jarg1_, int jarg2);
  public final static native int FaceDetectRect_left_get(long jarg1, FaceDetectRect jarg1_);
  public final static native void FaceDetectRect_top_set(long jarg1, FaceDetectRect jarg1_, int jarg2);
  public final static native int FaceDetectRect_top_get(long jarg1, FaceDetectRect jarg1_);
  public final static native void FaceDetectRect_right_set(long jarg1, FaceDetectRect jarg1_, int jarg2);
  public final static native int FaceDetectRect_right_get(long jarg1, FaceDetectRect jarg1_);
  public final static native void FaceDetectRect_bottom_set(long jarg1, FaceDetectRect jarg1_, int jarg2);
  public final static native int FaceDetectRect_bottom_get(long jarg1, FaceDetectRect jarg1_);
  public final static native long new_FaceDetectRect();
  public final static native void delete_FaceDetectRect(long jarg1);
  public final static native long new_FaceDetect();
  public final static native void delete_FaceDetect(long jarg1);
  public final static native boolean FaceDetect_init(long jarg1, FaceDetect jarg1_, int jarg2, int jarg3, String jarg4, byte[] jarg5);
  public final static native int FaceDetect_detectFacePos(long jarg1, FaceDetect jarg1_, byte[] jarg2, int[] jarg3, int jarg5, int jarg6);
  public final static native int FaceDetect_ROTATION_0_get();
  public final static native int FaceDetect_ROTATION_90_get();
  public final static native int FaceDetect_ROTATION_180_get();
  public final static native int FaceDetect_ROTATION_270_get();
  public final static native int FaceDetect_ROTATION_UNKNOWN_get();
  public final static native long new_CpuCheck();
  public final static native void delete_CpuCheck(long jarg1);
  public final static native boolean CpuCheck_NeonCheck(long jarg1, CpuCheck jarg1_);
}
